apiVersion: v1
kind: Namespace
metadata:
  name: paradise-bakes-cafe
  labels:
    name: paradise-bakes-cafe
    environment: production
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: paradise-bakes-cafe
  name: paradise-app-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints", "persistentvolumeclaims", "events", "configmaps", "secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets", "statefulsets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["autoscaling"]
  resources: ["horizontalpodautoscalers"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: paradise-app-rolebinding
  namespace: paradise-bakes-cafe
subjects:
- kind: ServiceAccount
  name: paradise-app-sa
  namespace: paradise-bakes-cafe
roleRef:
  kind: Role
  name: paradise-app-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: paradise-app-sa
  namespace: paradise-bakes-cafe
  labels:
    app: paradise-bakes-cafe
